version: "3.7"

services:
  dump1090-fa:
    build: ./dump1090-fa
    image: otofu/dump1090-fa
    container_name: dump1090-fa
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  fr24feed:
    build: ./fr24feed
    image: otofu/fr24feed
    container_name: fr24feed
    restart: unless-stopped
    volumes:
      - ./fr24feed/fr24feed.ini:/etc/fr24feed.ini
    logging:
      options:
        max-size: "10m"
        max-file: "3"
